secret:
    dbPort: ENC[AES256_GCM,data:TD1MjA==,iv:QePz6PN+IQF6CsHXGzutpcDurjxfHxULVfnszirv/6c=,tag:7cgtNeOksnX5MKX6dNdJDg==,type:int]
    dbName: ENC[AES256_GCM,data:dP+Sbw==,iv:HPGxbAR0WKYgL/6d90B2u9WtsVumwq9DcNheAM43feY=,tag:R8xOmXtCcCYEDsHPuO/n/w==,type:str]
    dbUser: ENC[AES256_GCM,data:IYTN1g==,iv:SiuTFANZ2xkAJaSkg/8H12V4eA2JQ8oedprtX0uRVVw=,tag:0uJIQX2XdkQhcleBiRB5MA==,type:str]
    dbPassword: ENC[AES256_GCM,data:LquJ6g==,iv:LZGWQc//4Lfdx7EX89+fH7bdmtER3KeYQFqQFqEU8sw=,tag:dWmVrTT/QKNO8SOzQbCMzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dFRrVE1XYzQ5dG43dkNm
            YWR3OXFzTWNueFJQekZmK0RlVVc3ZWlSdEF3CnUzNGpmNzZSdmYrL0xMNFZlTG1M
            akx2NDdPaVV2amVPSWE5bFY1R3VnU3cKLS0tIHRrRklvczR6Wm1PZlN5b3ZYeVJq
            ZkdzSDlCM2h2aDZzZGtiYzdMU210Q3MK7RZnbhOpa5TNAK27PU+I9QlSj3OaD64T
            A9zgI0V+hHpjnW5JctwPKLV/1sLC+EFsPkkaj9UESXpxnkkRpsR7nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d6kz4rrcghndrjasph4cevvwgkps0jr6xl6vmd59z5ng5plzrfps3yvlqt
    lastmodified: "2026-07-28T16:57:58Z"
    mac: ENC[AES256_GCM,data:v0f+OO8MwhgKGz7WV+gtKjj1QU9rmBRUJzJjruGSL4zeilgIXaOQSioXb+89QaHc31bkQyXzN9U9RBVjjb5icZOxnyy9sfc9QFgoFCrJA0iIn9RKWI+0J7GxQ3PThbHSOt2YrqrtSnk5455jTCGdNMyp4cQVPp9m86UkztWx3nA=,iv:4H0e7DUapkyYzkbjdJiOjvF/2eYhHmDcv6ArE+9g4Ls=,tag:+AC2yfCTLAQ1rdd9+nf2gQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
