secret:
    dbPort: ENC[AES256_GCM,data:xH6JjA==,iv:D1Gy3yi7vRj8Del1oATd3TEgRDHq0Wr1OLaY5+7WkXE=,tag:ZthtNQzS7wSRC0ryd+lFGQ==,type:int]
    dbHost: ENC[AES256_GCM,data:WtRlVyQOOPc=,iv:tmPj8vAFipzVtbAoUp9WnAAFgkKA8RPM6ac/aETHE40=,tag:M8Q9AQX/6yOAbmm9dW5NOg==,type:str]
    dbName: ENC[AES256_GCM,data:u+rO2g==,iv:btEzKaha/yEDwvbpO82SQT8nfvCHFCLzvVz9hmJ2Qio=,tag:GhS64cnEtOarN298miIiDw==,type:str]
    dbUser: ENC[AES256_GCM,data:B0wZ7w==,iv:iMvvgpUMABxEBNG2BC6hZ2usCvm/tBtCMWEpCaQyUMk=,tag:oUTSkSmKRmO2GDBDSR7WZw==,type:str]
    dbPassword: ENC[AES256_GCM,data:yuk50w==,iv:e4h2ykNMINQ38SCJMn3AEmfwpD3sgaVN0vprrWXFWks=,tag:80sJCoFEhUfR2ZfBg6CZ9Q==,type:str]
    test: ENC[AES256_GCM,data:0lVglg==,iv:Oc74JBhTfFB7DLasbHnnjPUi8MdlwGPl4lGq3f+DccI=,tag:54oM+n2rIjy5jq47HcdsDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU284Rkt2Z1BQZlNMZ1NO
            clE2a1I3VjhCczFYcUJ5QTZKc2tMczNBVmo4Ck12c2JHUVpramlwZ3pQRGFZampH
            NytTYVZ2YXJwd2g4eEt6a1RRLzlnOU0KLS0tIEhHUTVxQ2pOOUFFeDcxQjVERkNa
            WGFPbXJ3MElHWFYwQzFWNmRLZkEwakEKUB5HhULX+/IDn+YxVNTzChml577JRPk/
            LMHRhc4CmtneuzUiWw1LNcddQblw/iey8wcaTJtOJiWDgc4TPL4sZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d6kz4rrcghndrjasph4cevvwgkps0jr6xl6vmd59z5ng5plzrfps3yvlqt
    lastmodified: "2026-07-28T17:13:37Z"
    mac: ENC[AES256_GCM,data:eGLmp1UhRSC7ACNtNLi1EvU/fdfNkrbMWBLJlqqsSWvFVkIIE7OEL8a8a+mObkrhhVCwgc/yaE/7zijE1RFfe4lE7DTGizJZRePXbv2pJu+td2S7KJvoEM4YMb6WqiNnDu+RbRhuOX25uG9Zo1NMKZGrVpb9ysQdBCYDKvh9tjs=,iv:WLHCPwT7gw4497g/JR6LazFS/EdTE2lxI9x3GSAaQBI=,tag:Ffn5AMbJ8q3AqtTgxyBBVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
