#ENC[AES256_GCM,data:WTRUMmTn5vMrgMO6cXm4BrQgQ2rqhM364Z2wHewYfdEPP4OSh+PTX8HU6oaE42NqQU6+CK+ylFC4Tp3z+5DdNR90JKK9Qic9UpyixUrvKPxAxqSoPr4G0Mx6U5GdRDk2trlS1Y5D9kWg97Khx1HGsB9fGaWyQR0gDUVX0koPlKPX,iv:bPQOUkd/tTv2NTK8ddxjdyb58+GOnyHnRxkjAEkmf38=,tag:D8OSAfi3T2Kcbid5jDUKDQ==,type:comment]
#ENC[AES256_GCM,data:KvMlUH0X/mmlQb0TcVnn1WH+SWiEYjOsl3M4ptjUxd4QiRmSIRuW3Y1RBgYcnk2T5UDU52t7dCjunjG71Q==,iv:OxsymHttFheyPiiJvVkekWhgX6gyFMIT71IhkN4jBSE=,tag:rD4VfsMuvNGCLJWOaqIPdg==,type:comment]
#ENC[AES256_GCM,data:q8tW1JiualDUIFW25V/artFD25S287xl9MoxV11/Lto78Rz9/Q==,iv:bM490hKtjq25GFdPSlJ/+WObQjiBjoqYFSzqH2bHmm4=,tag:i3bS6Eji7Fo5IVzpcLpFwA==,type:comment]
#
#ENC[AES256_GCM,data:URIerN634B1Kxutp5HhlpmlQndxEgnURPSzBsQ2oJdsp7F03UT4RfLx5zJ91V2Dvx4dl506Kh90RrtfdkZoJp2YlxXqSEoNhfY05ZKSOsKkt/6NappG9Val+N8GSFFT2vw==,iv:tBjouzv8++FiVgAwPewwfVH0E10SlJ2rr1TXd0dCa0k=,tag:CTNn0THBZ5tYyFwGc0wXrw==,type:comment]
#ENC[AES256_GCM,data:C9wU8tu96RBe4gfHFmvaDoAIpA3R9fgjO/130LdLCIvF7quZZ7yy5DH7Qb2Pm/ltis9umysaD8jkYkHDifcmtRnXsCnf1bVwVh5v58GK1++ILH/tJvDvdmj22PV9hG1Zu6aJm+/wds2OhlciqRu0L2+fF6ULJIij4FW1ubnRGdBU6w==,iv:A5ER69zQ9caCuiLiWzSjlHJ1JL/rMAyej0A8WutYWgs=,tag:ICSNe0CTSxGuHKG0o8dfxQ==,type:comment]
#ENC[AES256_GCM,data:yX0OeuMW8kLvyN1sJY/k6tIFXEgZV2+LMMfXRdN+Bw==,iv:o049h3/2jj6q6A3pywtH99hChaDkz3sRTi6yignzMnQ=,tag:mejEYq2H+od3ONYnvuGBVg==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:o9gynA==,iv:H8J74sQPEBq2TyWDlOLMtXtT1KY6/YeJZHl74ijyJb0=,tag:ypFYd5QNjYQ5+UnuX4pD/A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ej6r1Q==,iv:SgpoVd5Osb9XPr49G79K6XshLBNhxq5dzLqLLmiVjRk=,tag:wTn0N9O9BjqISlp0faP7tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTjE2UUZOWEFRU1ZhWlhl
            UWtoMmdWeENyQnVCTlpvL1MrdmlsRFZ4V1c4CmZzcW1va0FKa3FIblM2RTBIQVZy
            Y1FJUnVVMEprQmp5bkRVYnRPdHNvTVkKLS0tIEo0NjlNaWJyN0lrNlRNWnNTQVdD
            QWJQdXFQV0pocG9tOU1DRVNwK0JzbXMKj/nb31RYT6Gk8tGB88CRzZZX0uEwgg20
            xLd0S14NcQxFN98QBVbi+DhWSE8aMsLijc8XeHFfpAaYLnAoHfRVyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d6kz4rrcghndrjasph4cevvwgkps0jr6xl6vmd59z5ng5plzrfps3yvlqt
    lastmodified: "2026-08-06T10:09:33Z"
    mac: ENC[AES256_GCM,data:wdhdjixZU9lmsDeYozQClyc8bg6SjXWY3dQGPxw7BREYzE9G984ySUZoXcwriGH3BSiisMAGVfioG1LxS8f0hq68F55YWcfGsTHLKzhK/sA/Vq8B/I0PIjWGbvnrY0d/0C4ix+H9NGgAKZUJ3RyMtU8Y0lunYoUU+ic4/MM3DzU=,iv:yfcwtR38vBlvhtHjN6HyxSg2YLZk5e7Us8aP8Ua6tQM=,tag:kcPOkkBq/Lt/sGpXN0S/FQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
