apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: backend-api
#          image: ${IMAGE}
          image: atpradical/todo-back:sha-3d1e5509fdadfd1a78c90f1e21c9b5d0303faa5f
          resources:
            requests:
              cpu: "60m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "120Mi"

          startupProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 12    # 12 × 5 сек = 1 минута на старт
            timeoutSeconds: 3
            periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /health
                port: 3000
              initialDelaySeconds: 0
              periodSeconds: 15
              failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /health/ready
                port: 3000
              initialDelaySeconds: 0
              periodSeconds: 10
              failureThreshold: 3

          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  selector:
    app: backend-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP