secret:
    dbName: ENC[AES256_GCM,data:ApRfDw==,iv:EVV22kHv4KfVtfqh5LInEN0LAHDfyQ2irKsj8XEItPQ=,tag:S4PuQ+w4WgkmH5K+E2QvcQ==,type:str]
    dbUser: ENC[AES256_GCM,data:9kTfQw==,iv:Hxd6IonSH/0NbRqSrvHAJhrdYpAD/N+s6w62i2MpIq8=,tag:jyxBh1/cdpFcuyzTj73TWw==,type:str]
    dbPassword: ENC[AES256_GCM,data:lek50Q==,iv:+Ahr5F8YUs+RCx3hYXrjsk7v2I1zwysXw96XCeFOtyU=,tag:jpNZ8vwYAkdRD+LKEZ6JOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY1ZjN1p0amNsR3RqSWdM
            NGNKM3puSXQya09CODE3cCt4N2IyN0FvZFdrCnZZeHA5WVluWmdrOWhyK3JlcURr
            U3o4dXdzak1UTGZVcmZTRG1tUVFnRHMKLS0tIERiWkt3eFRKTmRoOUdha1loZDJl
            WTdRV0JBWXZTUDNoTnluSCtVNURsMXcKBwCjZfc7+bc2tvyUDTT80zBe0qyQ9v/E
            k83CTC8WIKJB0WRnvAcVq00JlDHuO0ReMSSrb7GcoK9SloK2WVnmBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d6kz4rrcghndrjasph4cevvwgkps0jr6xl6vmd59z5ng5plzrfps3yvlqt
    lastmodified: "2026-07-28T16:57:38Z"
    mac: ENC[AES256_GCM,data:WRY50YhqJD4N3byTIMNRoKRuVI9DqRjyKHgK7y2Z4FBB/olRX1ww48P+hL1Y7IkSfpj1vFOcbSP0vyP+8Pvu0ri5sVzu3WJWP4sLUdvfDMPYOzpuHxE3ZAokHarn76aSzFADV9RmzrdUchtJad5KWZEVL4zuOO1cJ81NsE7S7lI=,iv:KcJfz5hvDjBUbuMef+XMBauq23Opvfu+0J3wIUFzXtc=,tag:M7mJsgHpN/vDghX17y9s8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
