#ENC[AES256_GCM,data:B4yEQUhrvwR2pTRkKn1l1P7tDQIgOIu7toPHwVlzvAfNER8EzIaM4YqGTiOiPml22i19i6bvlJ3Sok0v2y2Iv6l5inqj0VGnR3C/Ct1LeUlMVe7uSI+jVd9/Ws8xrYX4Zqf4MIdTUmVqI2X5ZRWH24uupaauMMAmO3JZI5ESJ+I=,iv:6B7BzDigG9NZY16Wo0Rb0qR+Bu2nuD88eCipirY9S1s=,tag:jcFPOIAFvJtM99cytj7n2Q==,type:comment]
#ENC[AES256_GCM,data:NR3Vc9wZtqx0veTI3DSIop91+pND1n4/vIxbq14iocpeVco6Ee8SLPTr/CONTuiLgv8b4EBsF5pqrMkcZgJXZy9t56dvAXEX1d+vXbKBJeMdVQGE4pS0GOK9QXPuhJ3WtSXkBRMTJXtWoP+w82jr4dybekkOe2UJ,iv:GdfMV0jvL0MF6QjcgXmlMnR6Iw7iGfHQnoUl5g/M8V0=,tag:n6Rq3zY5bStfYxV+WY0kqg==,type:comment]
#
#ENC[AES256_GCM,data:1jTodd5eKREL0xoOuogfw9Ockkw10iWpxpsfJwvmYPacgdi0mNmn95poffAmyg9yLvE6XgaAX1zf5a/+Vg1XqpA58A==,iv:oi/6pA4SRAdNNX2SOae+jeZYEFVhkeckVrmDkgqw3KU=,tag:11tPzCmMH2XtE+/Jm2hmYw==,type:comment]
#ENC[AES256_GCM,data:wpAIC9jIgDSwChbo5YzdBNNkvzmFahjn0f7MghjMHajjfPTH7VbDug==,iv:cLk0KB+d3jJvayJUwEtPcd+BcAcpe0NxRP5EIKAGryI=,tag:53at1AnQuy4XQDzVd6Oppg==,type:comment]
#
#ENC[AES256_GCM,data:TprYPRTCYGot9I7cvtkt31IUw9h2juwBrzopv8bnSJn92rPsfHXk26VQHn2u1BN1a/W02ivVIX8kAqMhvcAuH8VZN0tZy4dVKYGMy28pGoZZVCGoTYVQm54fn33hR1K016GcdayYQRwsop4rgcGmITMcEz2u,iv:zkW8pq/yCxdNcTbdF5j/KrmFN7Gsxu6cgKieuM1229k=,tag:ft+DZQ1rQ9icrOXyY3bcbQ==,type:comment]
#ENC[AES256_GCM,data:GWk0kLVeauEFw+Z72uQH1RF2pEil+4NJ8HJQlt+xzwc3LcvXy3UGq747oL9/kSMSImSeh5VECrmKIhZJV1dSTZJW5Mwz0EGZaSC97QYiHxfTSp9IPuY/ZPb3dksmnJDevB3rNYCl4t9QD/A4t4YiLCAU7dxWzL6w2fvGNcCeF3+jnLZFqyP2/nYtREDSq9U3SI5RFnk=,iv:HFcLcvjD/yhnLzAt4Op1tGJDGV+ZidxJ1m1K4nCGLB8=,tag:H/ld5pJPwIq4zoBc5eNNhA==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:N0S40Q==,iv:hS3P64p1hmP/5D8cal7seg1owwDBgS65fAh2Nhwb3f4=,tag:I9H+d86JCaz+8GEwH9H2oQ==,type:str]
    dbPassword: ENC[AES256_GCM,data:gQpA7w==,iv:PoF/kKuFJOD4Vm6LAA2wBt+BAPEukYdrpUKJNItxka8=,tag:dEdfcYe1dRY5lNFoWd0HRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObHF5Ty9aLzdYK01QTzl4
            WVQ5NFVKdUd0WFZBNlQ5MC9OVUd2eHFaYkFJCmhhbXJqcFBGTzRUYXJ4UkxMbk1O
            N0NrVUVudmJReEw3N0JSelpXOWpsT0kKLS0tIFFMK1BYRkNsOFRnRTc2WFJWVkUy
            TkhuL0NudjBFK2g2b0RJQWJtay9TUkEKv2KnuRmutA80IMCmIfCOqKAiUN6AqT8L
            ZmE/XA8/sMKZrKzXl00olIR9pxJs2vckNqLjzs5NPJHussg80U+enQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d6kz4rrcghndrjasph4cevvwgkps0jr6xl6vmd59z5ng5plzrfps3yvlqt
    lastmodified: "2026-08-06T10:08:22Z"
    mac: ENC[AES256_GCM,data:OSYKB03Qk/WGxNdsA4AeGJ9R0iJHHvjJRtNCKQT61zNOPZZumSEnbkValoT6CAdGsPUnP0NL9jCh5AtyiKuXB5Eq5wCiFFp73t+C1ZlM0lnTsLgTt5ogdyRrLLEU+VWMQQiIJSKVopLkwNlfdOsDPI4bpxKNgpv6FZls9VEVQAQ=,iv:g78QGyAabE5vVYHdv0JNKtxGEUgHpoiK6zUsoURb2+A=,tag:BBbQF0sNA6NdmpRyny7Z3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
