secret:
    dbName: ENC[AES256_GCM,data:ApRfDw==,iv:EVV22kHv4KfVtfqh5LInEN0LAHDfyQ2irKsj8XEItPQ=,tag:S4PuQ+w4WgkmH5K+E2QvcQ==,type:str]
    dbUser: ENC[AES256_GCM,data:9kTfQw==,iv:Hxd6IonSH/0NbRqSrvHAJhrdYpAD/N+s6w62i2MpIq8=,tag:jyxBh1/cdpFcuyzTj73TWw==,type:str]
    dbPassword: ENC[AES256_GCM,data:lek50Q==,iv:+Ahr5F8YUs+RCx3hYXrjsk7v2I1zwysXw96XCeFOtyU=,tag:jpNZ8vwYAkdRD+LKEZ6JOA==,type:str]
    test: ENC[AES256_GCM,data:h5Girg==,iv:zZ/Cg+iHlGctsI7hWgdQIb6tXvUmazRlbObxVs1SsWY=,tag:kThU8DHOmhTD8SyE7LlgqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY1ZjN1p0amNsR3RqSWdM
            NGNKM3puSXQya09CODE3cCt4N2IyN0FvZFdrCnZZeHA5WVluWmdrOWhyK3JlcURr
            U3o4dXdzak1UTGZVcmZTRG1tUVFnRHMKLS0tIERiWkt3eFRKTmRoOUdha1loZDJl
            WTdRV0JBWXZTUDNoTnluSCtVNURsMXcKBwCjZfc7+bc2tvyUDTT80zBe0qyQ9v/E
            k83CTC8WIKJB0WRnvAcVq00JlDHuO0ReMSSrb7GcoK9SloK2WVnmBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d6kz4rrcghndrjasph4cevvwgkps0jr6xl6vmd59z5ng5plzrfps3yvlqt
    lastmodified: "2026-07-28T17:17:11Z"
    mac: ENC[AES256_GCM,data:MnmTNq8vRMWcwDZ7MzVmE0Eo5KJIzWpjkFKK1LD3hn2+LqF/NCnfLmPStRFxvx0JRBf+rinax9jiuO1HJ8EQzspsDAW/CGMK2P4//nkzegtS2IpotNuFX0uHl0rW9OGyL/wRxp8Ng7KIOO9hDxmdO+2DSp7flhxBs58tFlDa2+I=,iv:nUiNxiKU38ZgdH22ppE3/YeO6PDdCTa3h62ch/L7bTA=,tag:KrCALeOpph7z37G4grXyew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
