apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_HOST: {{ .Values.secret.dbHost | quote }}
  DB_PORT: {{ .Values.secret.dbPort | quote }}
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  DB_NAME: {{ .Values.secret.dbName | quote }}